# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones


    # Payment processors from the systemeio/test-for-candidates package
    Systemeio\TestForCandidates\PaymentProcessor\PaypalPaymentProcessor: ~
    Systemeio\TestForCandidates\PaymentProcessor\StripePaymentProcessor: ~

    # Adapters for payment processors
    App\Service\Payment\PaypalPaymentProcessorAdapter:
        arguments:
            $processor: '@Systemeio\TestForCandidates\PaymentProcessor\PaypalPaymentProcessor'

    App\Service\Payment\StripePaymentProcessorAdapter:
        arguments:
            $processor: '@Systemeio\TestForCandidates\PaymentProcessor\StripePaymentProcessor'

    # Payment processor factory
    App\Service\Payment\PaymentProcessorFactory:
        arguments:
            $paypal: '@App\Service\Payment\PaypalPaymentProcessorAdapter'
            $stripe: '@App\Service\Payment\StripePaymentProcessorAdapter'

    # Discount strategies
    app.fixed_discount_strategy:
        class: App\Service\Coupon\FixedDiscountStrategy
        public: true

    app.percentage_discount_strategy:
        class: App\Service\Coupon\PercentageDiscountStrategy
        public: true

    # Price calculator service
    App\Service\PriceCalculatorService:
        arguments:
            $fixedStrategy: '@app.fixed_discount_strategy'
            $percentageStrategy: '@app.percentage_discount_strategy'

    # Payment service
    App\Service\PaymentService:
        arguments:
            $factory: '@App\Service\Payment\PaymentProcessorFactory'

    # Price calculator factory (optional)
    App\Service\PriceCalculatorFactory:
        arguments:
            $fixedStrategy: '@app.fixed_discount_strategy'
            $percentageStrategy: '@app.percentage_discount_strategy'
            $productRepository: '@App\Repository\ProductRepository'
            $couponRepository: '@App\Repository\CouponRepository'